apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  domain:
    devices:
      graphics:
      - type: spice
      interfaces:
      - type: network
        source:
          network: default
      video:
      - type: qxl
      disks:
      - type: PersistentVolumeClaim
        snapshot: external
        device: disk
        driver:
          name: qemu
          type: raw
          cache: none
        source:
          name: disk-alpine
        target:
          dev: vda
      consoles:
      - type: pty
    memory:
      unit: MB
      value: 64
    os:
      type:
        os: hvm
    type: qemu
