apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  selector:
    matchLabels:
      guest: testvm
  template:
    metadata:
      labels: 
        kubevirt.io/size: small
    spec:
      domain:
        devices:
          disks:
            - name: registrydisk
              volumeName: registryvolume
              disk:
                bus: virtio
            - name: cloudinitdisk
              volumeName: cloudinitvolume
              disk:
                bus: virtio
          interfaces:
          - bridge: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: registryvolume
          registryDisk:
            image: kubevirt/cirros-registry-disk-demo
        - name: cloudinitvolume
          cloudInitNoCloud:
            userDataBase64: SGkuXG4= 
    devices: {}
